"""
Tests for the filestream module
"""


def test_load_cipher():
    """
    Test the load file method
    """
    from util.filestream import load_file
    assert (load_file("codes/01-OPGAVE-viginereplus.txt") ==
            "YZDCHLBZIANYLLXRZMMPMOVZCHWDCAKVJHAPUUNVHTGPNAEIILWXNUNLZMLGCLIIOLDZUAVNZTMPMLIIOGGRUQZPDOWLGLDZCALADV"
            "VXCXWYUJRSIADKMKUMNEGLCSNICXVYTPERQZGHILVJASDRHLEIMKGPEUVVZXWSGBWEJZSSFYNIYSVTNUVLOGMLHWKIYHYTYLUOCTS"
            "CYAVIVWKHMKEIYADPYYERIHWPHSFEPXWTEPKEEUSZLFKAPRKZXVZNYZRDWFWUAREPGNVGVUXOCVLFHZEMIFXIKSVOGAPVHVXZHGP"
            "LVEMNWWEDAERMXLEFDCSZKNXHAWIJMLPNVZEVZLFGKVEMDYCBHXWZEARXAXGOKFYZHCICXETAKVSZHWCYYFMJEWOZIEHQMVPU"
            "PSROGJPNVWIJTWXXHJIZALZMUVXHDSTYPCEMXFNHHEEGELEBBKQZMSZYLBIJNFVMTUPKGJDTVQOIGWHXKROZTFJZBFOXYJAOXXQ"
            "QDVXDDVPGKKVZTBZHKUKJSACGRVVDCKRUBMJZNDYGYVVGLDXCYELCHEPFUASMXAEYUVIIKGEYSCSJLWTAYUOKLFLWOVIZHLSCLGRI"
            "OLPQVVVZXWTYBEMEKHYAYUJPXKYICZWPXWRYTEHMMCUULVTNXDZCHUWIHERTLRNDNZYZTKNOMWSELZIGXCRYKEVVTVSCYCDMWWFJ"
            "NVDZBAZMDIMVBYMHZLAVTCEAUJLYLKXOHFCYWUSZSZZYLELIGRAHLZSJYXXNYZRJGSYPLLEOTJRDZFRMUKZZVNICKWPNKVHDLHCZ"
            "HVIJMWZIJZYVMRSXLDKZLKSIADRNGVTUNJQIXUPHUCVIXMAPKVWJMYCCPCSZLMGOVCAOTDLNHVEIXWQCUKQZKEXWZBIVMAWHHRXZXF"
            "LIVVXNXWWAOGEBWGZEAIHPDLZYOERHVHEHUKIYKUPAIVIZXWNNBVZMEVPNLVIYBTVAJBWPHUVXITTPURLKVIAOVUEWZHVTTLFSIHC"
            "FURIHYWAPYHVIJCJPHAVIBXLPYYVSZGBPQMZMHTDWCKVKCTWEMYXIOFAOIURHZHAPQPUHEKTZLAYVZCWTBLYMOWZONKKSFBWZYYFR"
            "MDBYYAVRZEGEYGVEJXFLMYEHJBLLNUMTOMTPMAEHDWCNYLVIOMWCEBKQIWJTNPUINVLLMGVTZTDSHVEXFUDOILRHOOELLLZHFOSTUY"
            "ZRLHRSOZTZLYZBVOKKNQRKIZXBYJLUHAPWPYVSYZHBHIQYSVHNPUPEOZXBLZHQIWXSCIAAKOPKPYMMHOOWTPVVDBDKEYUZIJKJLWV"
            "VIZWWYECRIIWVDNHVIJXJPYAFDGOWEYKMEQBFPHHYIZTJPNLMLYGNVYLVIZOVOLULRYKLWJHGFIPJPBVWRZNZVYBTSYMSGHUXIVEA"
            "ETIRIZWFZUQVENMWDANXQZWWYYLYOICWALZSLZXDPUVZXDAVPUARMZHWLUUZPFBNTYVXPOGMOCPIVJWVTNRZIUMJDNYYIBEWTJURXY"
            "WVNVCVMIXWPXZLHBHLSXYKHVGSOCKVSEGWPDPELOMJSIUJXBXSUNZMPJPLLHTVKOTCXCNERUTVPXHCPRUVRYLDOIGAZUKZICMWYHHV"
            "XZLYPFLMEHXWZLUEIIBVEUNRSHGWSLQVEKAWEUAFTGWSUUHZIVKAHYUVVHXJECPDRFXARIBVRHPRPB"
            )
